# Generated by Django 3.1.4 on 2021-01-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=20)),
                ('fullText', models.TextField(blank=True, null=True)),
                ('favoriteNumber', models.IntegerField(default=0)),
                ('retweetNum', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
    ]
