# Generated by Django 3.1.4 on 2021-01-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='sentiment',
            field=models.CharField(default='no data', max_length=20),
            preserve_default=False,
        ),
    ]
