# Generated by Django 3.1.4 on 2021-01-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_tweets_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='date',
            field=models.CharField(default='no data', max_length=60),
            preserve_default=False,
        ),
    ]
