# Generated by Django 3.1.4 on 2021-01-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_tweets_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='fullText',
            new_name='tweet',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='favoriteNumber',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='retweetNum',
        ),
        migrations.AddField(
            model_name='tweets',
            name='twhisper_user',
            field=models.CharField(default='nodata', max_length=20),
            preserve_default=False,
        ),
    ]
