# Generated by Django 3.1.4 on 2021-01-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_tweets_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='user',
            field=models.CharField(max_length=64),
        ),
    ]
