# Generated by Django 3.1.4 on 2021-01-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210126_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='deneme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=20)),
                ('tweet', models.CharField(max_length=300)),
                ('twhisper_user', models.CharField(max_length=20)),
                ('sentiment', models.CharField(max_length=20)),
            ],
        ),
    ]
