# Generated by Django 3.1.4 on 2021-01-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_deneme'),
    ]

    operations = [
        migrations.AddField(
            model_name='deneme',
            name='user',
            field=models.CharField(default='nodata', max_length=64),
            preserve_default=False,
        ),
    ]
