# Generated by Django 3.1.4 on 2021-01-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_deneme_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='deneme',
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='user',
        ),
        migrations.AddField(
            model_name='tweets',
            name='author',
            field=models.CharField(default='rohat', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweets',
            name='date',
            field=models.IntegerField(default=0),
        ),
    ]
